
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
import main

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\tcoll\WeatherGUI\WeatherGUI\build\assets\frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("1440x1080")
window.configure(bg = "#DDDDDD")

canvas = Canvas(
    window,
    bg = "#DDDDDD",
    height = 1080,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    1.4210854715202004e-14,
    0.0,
    1080.0,
    720.0,
    fill="#87CEEB",
    outline="")

canvas.create_rectangle(
    1080.0,
    5.684341886080802e-14,
    1440.0,
    720.0,
    fill="#BBBBBB",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    720.0,
    1440.0,
    1080.0,
    fill="#FF7A00",
    outline="")

canvas.create_rectangle(
    724.9999999999999,
    725.0,
    1075.0,
    1075.0,
    fill="#252525",
    outline="")

canvas.create_rectangle(
    1085.0,
    725.0,
    1435.0,
    1075.0,
    fill="#252525",
    outline="")

canvas.create_rectangle(
    364.9999999999999,
    725.0,
    714.9999999999999,
    1075.0,
    fill="#252525",
    outline="")

canvas.create_text(
    1085.0,
    4.999999999999943,
    anchor="nw",
    text="Insert Fun text here",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_rectangle(
    4.999999999999886,
    725.0,
    354.9999999999999,
    1075.0,
    fill="#252525",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1147.0,
    787.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    786.9999999999999,
    787.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    426.9999999999999,
    787.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    125.00000000000011,
    125.00000000000006,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    66.99999999999989,
    787.0,
    image=image_image_5
)

canvas.create_text(
    124.99999999999989,
    737.0,
    anchor="nw",
    text="Temp:\nRealFeel: Humid:\nRain %:\nSnow %:",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    1210.0,
    737.0,
    anchor="nw",
    text="Temp:\nRealFeel: Humid:\nRain %:\nSnow %:",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    849.9999999999999,
    737.0,
    anchor="nw",
    text="Temp:\nRealFeel: Humid:\nRain %:\nSnow %:",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    489.9999999999999,
    734.0,
    anchor="nw",
    text="Temp:\nRealFeel: Humid:\nRain %:\nSnow %:",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

canvas.create_rectangle(
    9.999999999999886,
    850.0,
    349.9999999999999,
    1070.0,
    fill="#A2A2A2",
    outline="")

canvas.create_rectangle(
    1090.0,
    850.0,
    1430.0,
    1070.0,
    fill="#A2A2A2",
    outline="")

canvas.create_rectangle(
    729.9999999999999,
    850.0,
    1070.0,
    1070.0,
    fill="#A2A2A2",
    outline="")

canvas.create_rectangle(
    369.9999999999999,
    850.0,
    709.9999999999999,
    1070.0,
    fill="#A2A2A2",
    outline="")

canvas.create_rectangle(
    4.999999999999886,
    249.99999999999994,
    1075.0,
    715.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    409.9999999999999,
    4.999999999999943,
    anchor="nw",
    text="Temperature:\nRealFeel: Humidity:\nWind:\nRain:\nSnow:\nPressure:\nWeather Conditions:\n",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    219.9999999999999,
    74.99999999999994,
    anchor="nw",
    text="99°F",
    fill="#FFFFFF",
    font=("PTSerif Caption", 64 * -1)
)
window.resizable(False, False)
window.mainloop()
