
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
import main
from datetime import datetime, timedelta
from datetime import datetime, timedelta

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
#from tkinter import WORD, Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\tcoll\WeatherGUI\WeatherGUI\build\assets\frame0")
DIRECTIONS = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW']

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def base(canvas):
    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0,
        0.0,
        1080.0,
        720.0,
        fill="#87CEEB",
        outline="")

    canvas.create_rectangle(
        1080.0,
        80,
        80,
        1440.0,
        720.0,
        fill="#BBBBBB",
        outline="")

    canvas.create_rectangle(
        0,
        720.0,
        1440.0,
        1080.0,
        fill="#FF7A00",
        outline="")

    canvas.create_rectangle(
        725,
        725.0,
        1075.0,
        1075.0,
        fill="#252525",
        outline="")

    canvas.create_rectangle(
        1085.0,
        725.0,
        1435.0,
        1075.0,
        fill="#252525",
        outline="")

    canvas.create_rectangle(
        365,
        725.0,
        715,
        1075.0,
        fill="#252525",
        outline="")

    canvas.create_rectangle(
        5,
        725.0,
        355,
        1075.0,
        fill="#252525",
        outline="")

    canvas.create_rectangle(
        10,
        850.0,
        350,
        1070.0,
        fill="#A2A2A2",
        outline="")

    canvas.create_rectangle(
        1090.0,
        850.0,
        1430.0,
        1070.0,
        fill="#A2A2A2",
        outline="")

    canvas.create_rectangle(
        730,
        850.0,
        1070.0,
        1070.0,
        fill="#A2A2A2",
        outline="")

    canvas.create_rectangle(
        370,
        850.0,
        710,
        1070.0,
        fill="#A2A2A2",
        outline="")
    
    canvas.create_rectangle(
        5,
        250,
        1075.0,
        715.0,
        fill="#000030",
        outline="")
    return canvas

def show_days(canvas, Temp1, Temp2, Temp3, Temp4, RF1, RF2, RF3, RF4, Humid1, Humid2, Humid3, Humid4, Code1, Code2, Code3, Code4):
    #Day 1
    time = datetime.now().replace(minute=0, second=0)
    time2 = datetime.now().replace(minute=0, second=0) + timedelta(days=1)
    time3 = datetime.now().replace(minute=0, second=0) + timedelta(days=2)
    time4 = datetime.now().replace(minute=0, second=0) + timedelta(days=3)
    time = datetime.now().replace(minute=0, second=0)
    time2 = datetime.now().replace(minute=0, second=0) + timedelta(days=1)
    time3 = datetime.now().replace(minute=0, second=0) + timedelta(days=2)
    time4 = datetime.now().replace(minute=0, second=0) + timedelta(days=3)
    canvas.create_text(
        125,
        737.0,
        anchor="nw",
        text="Temp: " + Temp1 + "°F"
        "\nRealFeel: " + RF1 + "°F" +
        "\nHumidity: " + Humid1 + "%" +
        "\nWeather Conditions: " + str(Code1) + "\n" +
        time.strftime("%c"),
        fill="#FFFFFF",
        font=("Times", 16 * -1),
        font=("Times", 16 * -1),
        width=220
    )

    #Day 2
    canvas.create_text(
        490,
        734.0,
        anchor="nw",
        text="Temp: " + Temp2 + "°F" +
        "\nRealFeel: " + RF2 + "°F" +
        "\nHumidity: " + Humid2 + "%" +
        "\nWeather Conditions: " + str(Code2) + "\n" +
        time2.strftime("%c"),
        fill="#FFFFFF",
        font=("Times", 16 * -1),
        font=("Times", 16 * -1),
        width=220
    )

    #Day 3
    canvas.create_text(
        850,
        737.0,
        anchor="nw",
        text="Temp: " + Temp3 + "°F" +
        "\nRealFeel: " + RF3 + "°F" +
        "\nHumidity: " + Humid3 + "%" +
        "\nWeather Conditions: " + str(Code3) + "\n" +
        time3.strftime("%c"),
        fill="#FFFFFF",
        font=("Times", 16 * -1),
        font=("Times", 16 * -1),
        width=220
    )

    #Day 4
    canvas.create_text(
        1210.0,
        737.0,
        anchor="nw",
        text="Temp: " + Temp4 + "°F" +
        "\nRealFeel: " + RF4 + "°F" +
        "\nHumidity: " + Humid4 + "%" +
        "\nWeather Conditions: " + str(Code4) + "\n" +
        time4.strftime("%c"),
        fill="#FFFFFF",
        font=("Times", 16 * -1),
        font=("Times", 16 * -1),
        width=220
    )
    return canvas

#Current Weather
def show_cur(canvas, temp, rf, humid, windS, windD, precip, pressure, weatherCode):
    direction = round(windD/22.5) if windD<348.5 else 361
    canvas.create_text(
        500,
        25,
        25,
        anchor="nw",
        text=("RealFeel: " + str(rf) + "°F" +
            "\nHumidity: " + str(humid) + "%" +
            "\nWind: " + str(windS) + " MPH " + str(DIRECTIONS[direction % 16]) +
            "\nPrecipitation Chance: " + str(precip) + "%" +
            "\nPressure: " + str(pressure) + "hPa" +
            "\nWeather Conditions: " + str(weatherCode)),
        fill="#000000",
        font=("Times", 28 * -1)
        font=("Times", 28 * -1)
    )

    #Current Temperature
    canvas.create_text(
        220,
        75,
        anchor="nw",
        text= str(temp) + "°F",
        fill="#FFFFFF",
        font=("PTSerif Caption", 64 * -1)
    )
    return canvas

def show_facts(canvas):
    canvas.create_text(
    1085.0,
    85,
    85,
    anchor="nw",
    text="Insert Fun text here",
    fill="#000000",
    font=("Inter", 16 * -1)
    )

    return canvas


